require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - binstub/**/*
    - exe/**/*
    - generated/**/binstub/*
    - generated/**/exe/**/*
    - vendor/**/*
    - Gemfile*
    - Rakefile
    - README.md
  NewCops: enable
  TargetRubyVersion: 3.1.3

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Exclude:
    - nugem.gemspec
  Max: 30

Metrics/ClassLength:
  Exclude:
    - spec/*.rb

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - Rakefile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Mode: conservative

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

RSpec/FilePath:
  IgnoreMethods: true
  SpecSuffixOnly: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 15
